name = "Robusted"
license = "MIT"
licenselink = "https://github.com/nboughton/hugo_theme_robusted/blob/master/LICENSE"
description = "Robusted is blog theme for hugo, originally based on Daisuke Tsuji's Robust theme."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Nick Boughton"
    homepage = "http://www.nboughton.uk"

