name = "Robusted"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_robust/blob/master/LICENSE.md"
description = "Robusted is blog theme for hugo, originally based on Daisuke Tsuji's Robust theme."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Nick Boughton"
    homepage = "http://www.nboughton.uk"

